name: test

on:
  workflow_dispatch:

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  notebook-tests:
    runs-on: ubuntu-latest
    services:
      jupyter-tm351:
        image: ouvocl/vce-tm351-monolith:22j-b2
        ports:
        - 8888:8888
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install playwright dependencies
      run: |
        npx playwright install-deps
        npm install -D @playwright/test

    # Test setup
    - name: Test screenshots
      run: |
        npx playwright test

